server:
  port: 9501
management:
  security:
    enabled: false
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/techragesh/springboot-cloud-config-demo/
          search-paths: cloudconfigrepo
          username: techragesh
          password: Rithu123#
  application:
    name: cloudconfigserver