server:
  port: 9501
management:
  security:
    enabled: false
spring:
  cloud:
    config:
      server:
        git:
          uri: /home/ragesh/data/learn/github/springboot-cloud-config-demo
          search-paths: cloudconfigrepo
  application:
    name: cloudconfigserver