server:
  port: 9502
management:
  security:
    enabled: false
spring:
  cloud:
    config:
      uri: http://localhost:9501
  profiles:
    active: development
  application:
    name: cloudconfigclient